config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  get "/welcome", to: "welcome#index"
  root "welcome#index"
  get "/portfolio", to: "users#my_portfolio"
  get "search_stock", to: "stocks#search"
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      secret_token: "Tsk_2083d2a859004089a2db65bf2f2e3c3e",
      endpoint: "https://sandbox.iexapis.com/v1",
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
  stock = Stock.check_db(ticker_symbol)
  return false unless stock
  stocks.where(id: stock.id).exists?    
  end
  
  def under_stock_limit?
  stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
  under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous!"
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend= User.find(params[:friend])
    current_user.friendships.build(friend_id: friend_id)
    if current_user.save
      flash[:notice]= "Following Friend"
    else
      flash[:alert]= "something wrong with tracking request"
      redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id:  params[:id]).first
    friendship.destroy
    flash[:notice]= "Stopped Following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: "users/result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: "users/result" }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: "users/result" }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to portfolio_path
  end
  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to portfolio_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks= current_user.stocks
  end

  def my_friends
    @q = current_user.friends.ransack(params[:q])
    @friends = @q.result(distinct: true)
    
      respond_to do |format|
        format.html
        format.js { render partial: 'users/friend_result' }
      end
    
  end

  def show
    @user= User.find(params[:id])
    @tracked_stocks= @user.stocks
  end

  def search
    
    # if params[:friends].present?
    # @friend = params[:q]
    #   if @friend
    #     respond_to do |format|
    #       format.html
    #       format.js { render partial: 'users/friend_result' }
    #     end
    #   else
    #     respond_to do |format|
    #       flash.now[:alert] = "Couldn't find user"
    #       format.html
    #       format.js { render partial: 'users/friend_result' }
    #     end
    #   end  
    # else
    #   flash.now[:alert] = "Enter name or email to search"
    #   format.html
    #   format.js { render partial: 'users/friend_result' }
    # end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<% if friends.present? %>
  <div class="row">
    <div class="col-9">  
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% friends.each do |friend| %>
            <tr>
              <td><%= friend.email %></td>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= link_to 'View profile', user_path(friend), 
                                            class: 'btn btn-sm btn-success' %>
              <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                            class: 'btn btn-sm btn-warning' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <% # <a class="navbar-brand" href="#">Finance Tracker</a> %>
        <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
        <% if current_user %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= "active" if request.path == portfolio_path %>">
                        <%= link_to "My Portfolio", portfolio_path, class: "nav-link" %>
                    </li>

                    <li class="nav-item <%= "active" if request.path == my_friends_path %>">
                        <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                            <i class="fa fa-edit"></i> Edit profile
                        <% end %>
                        
                        </div>
                    </li>

                </ul>
                <ul class="navbar-nav  ml-auto">
                     <li class='nav-item user-name'>
                       <i class="fa fa-user"></i>
                       <%= current_user.full_name %> 
                    </li>
                    <li class="nav-item">
                        <%= link_to("Logout", destroy_user_session_path, class: "btn btn-danger logout-button", method: :delete) %>
                    </li>
                </ul>
               
        
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
		<%= render "layouts/navigation" %>
		<div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
		</div>
  </body>
</html>

app/views/stocks/_list.html.erb
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker%></th>
              <td><%= stock.name%></td>
              <td><%= stock.last_price%></td>
              <td>
                <% if current_user.can_track_stock?(stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
    <% elsif current_user.id != @user.id  %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? && !current_user.stock_already_tracked?(stock.ticker) %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
              <% if current_user.id == @user.id %>
              <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-warning' %>
              <%end%>
                                          </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render "layouts/messages" %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
  <% @friends.each do |friend| %>
    <strong>Name: </strong> <%= friend.full_name %>
    <strong>Email: </strong> <%= friend.email %>
    <strong>Profile: </strong> <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
    <% if current_user.not_friends_with?(friend.id) %>
      <%= link_to "Follow friend?", friendship_path(friend: friend),
                  class: "btn btn-sm btn-success", method: :post %>
    <% else %>
    <span class="badge badge-secondar">
      You are Friends
    </span>
    <% end %>
    <% end %>
  </div>
<% end %> 

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render "users/friend_result.html" %>' 

app/views/users/_result.html.erb
<div class="results-block">
  <%= render "layouts/messages" %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong>
    <%= @stock.ticker %>
    <strong>Name: </strong>
    <%= @stock.name %>
    <strong>Price: </strong>
    <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? && !current_user.stock_already_tracked?(@stock.ticker) %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
 document.querySelector('#results').innerHTML= '<%= j render "users/result.html" %>'

app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
 </div>

<%= search_form_for @q,remote: true, url: my_friends_path, class: "form-group" do |f| %>
  <div class="form-group row">
    <div class="col-sm-9">
      <%= f.search_field :first_name_or_last_name_or_email_cont, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.submit %>
    </div>
  </div>
<% end %>

<div id="friend-results"></div> 

<%= render "friends/list", friends: @friends %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>

  <%= form_tag search_stock_path, remote: true, method: :get do %>

    <div class="form-group row">

      <div class="col-sm-9">
        <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: "true", class: "form-control form-control-lg" %>
      </div>

      <div class="col-sm-3 ">
        <%= button_tag type: "submit", class: "btn btn-success search_icon" do %>
          <i class="fa fa-search fa-2x"></i>
        <% end %>
      </div>

    </div>

  <% end %>

</div>
<div id="results">

</div>
<% if !@tracked_stocks.empty? %>
<%= render 'stocks/list' %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.blank?  %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %> 

app/views/welcome/index.html.erb
<h1> hello finance tracker</h1>
<p>Create a welcome page</p>